{% set name = "mpl-qtthread" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpl-qtthread-{{ version }}.tar.gz
  sha256: 31d73c413e06efe5a5176bcdf1b68e774c0232277d004530a79cb7907e1357e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib
    - pyqt

test:
  imports:
    - mpl_qtthread
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tacaswell/mpl-qtthread
  summary: A Matplotlib backend for working with (Q)Threads and Qt
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
